apiVersion: v1
kind: Pod
metadata:
  name: busybusy
spec:
  containers:
  - image: busybox
    name: busybox-1
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /busy
      name: test
  
  - image: busybox
    name: busybox-2
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /box
      name: test
  
  volumes:
  - name: test
    emptyDir: {}


# 
#  Test the shared folders:
#  look at the folders first in each container inside the pod
#  busybox-1 container:
#  kubectl exec -ti busybusy -c busybox-1 -- ls
#  you will see a list of fodlers, the one you are interested in is "busy"
#  kubectl exec -ti busybusy -c busybox-1 -- ls -l busy
# Response: total 0
#  busybox-2 container:
#  kubectl exec -ti busybusy -c busybox-2 -- ls
#  you will see a list of fodlers, the one you are interested in is "box"
#  kubectl exec -ti busybusy -c busybox-2 -- ls -l box
#
# Test the link between the two by adding a file via the one container:
# kubectl exec -ti busybusy -c busybox-1 -- touch /busy/test 
# View the file through the other container:
# kubectl exec -ti busybusy -c busybox-1 -- ls -l box
# kubectl exec -ti busybusy -c busybox-2 -- ls -l box

# Notice that in the first container, busybox-1 the folder was called "busy" 
# but still linked to the same location as busybox-2
# response:
# total 0
# -rw-r--r--    1 root     root             0 Aug  8 13:39 test