# If you use digital ocean's managed kubernetes clusters
# Then the block storage will get created by default
# you don't need to set up the block storage, the PVC request will create it
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: expose-wordpress
  name: wordpress-svc
spec:
  ports:
  # - nodePort: 30703
  #   port: 80
  #   protocol: TCP
  #   targetPort: 80
  #   name: wordpress
  - nodePort: 30700
    port: 80
    protocol: TCP
    name: wordpress-port
  selector:
    app: wordpress
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
# Don't hardcode the db password like this
# There are better ways to add secrets to kubernetes
# Ths is just for the example
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dm9kYWNvbTEyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secrets
type: Opaque
data:
  PMA_HOST: bXlzcWw=
  PMA_PORT: MzMwNg==
---
apiVersion: v1
kind: Secret
metadata: 
  name: wordpress-secrets
data:
  WORDPRESS_DB_HOST: bXlzcWw6MzMwNg==
  WORDPRESS_DB_USER: cm9vdA==
  WORDPRESS_DB_PASSWORD: dm9kYWNvbTEyMw==
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_TABLE_PREFIX: d3Bf
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
  labels: 
    app: wordpress
spec:
  containers:
    - name: curl
      image: ubuntu
      command: 
        - sleep
        - "3600" 
    # MYSQL
    - name: mysql
      image: mysql:5.6
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: MYSQL_ROOT_PASSWORD
      volumeMounts:
        - name: database-storage
          mountPath: /database

    # PHPMYADMIN
    - name: phpmyadmin
      image: phpmyadmin/phpmyadmin:4.6.0-1
      env: 
      - name: PMA_HOST
        valueFrom:
          secretKeyRef:
            name: phpmyadmin-secrets
            key: PMA_HOST
      - name: PMA_PORT
        valueFrom:
          secretKeyRef:
            name: phpmyadmin-secrets
            key: PMA_PORT
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: MYSQL_ROOT_PASSWORD
      # ports:
      # - containerPort: 80
      #   hostPort: 8080
      #   protocol: TCP
      #   name: phpmyadminport

    # WORDPRESS
    # - name: wordpress
    #   image: wordpress:4.8-apache
    #   env:
    #   - name: WORDPRESS_DB_HOST
    #     valueFrom:
    #       secretKeyRef:
    #         name: wordpress-secrets
    #         key: WORDPRESS_DB_HOST
    #   - name: WORDPRESS_DB_USER
    #     valueFrom:
    #       secretKeyRef:
    #         name: wordpress-secrets 
    #         key: WORDPRESS_DB_USER
    #   - name: WORDPRESS_DB_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: wordpress-secrets
    #         key: WORDPRESS_DB_PASSWORD
    #   - name: WORDPRESS_DB_NAME
    #     valueFrom:
    #       secretKeyRef:
    #         name: wordpress-secrets
    #         key: WORDPRESS_DB_NAME
    #   - name: WORDPRESS_TABLE_PREFIX
    #     valueFrom:
    #       secretKeyRef:
    #         name: wordpress-secrets
    #         key: WORDPRESS_TABLE_PREFIX

  volumes:
    - name: database-storage
      persistentVolumeClaim:
        claimName: csi-pvc
